version: "3.9"
services:
    postgre:
        image: postgres:15.2
        container_name: postgres
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pswd
        networks:  
            - transcendence
        volumes:
            - /home/tchapp/dbdata:/var/lib/postgresql/data
        restart: always

    back:
        tty: true
        build: docker/back
        ports:
            - '3000:3000'
        container_name: back
        volumes:
            - "./nestjs:/usr/src/app"
        networks:
            - transcendence
        working_dir: /usr/src/app
        restart: always

networks:
    transcendence:
        #driver: bridge
volumes:
    back: